// The template registry: how to fill and sign each VERSION of a vendor's form.
//
// A blank form is identified by a fingerprint of its structure (page count, AcroForm field
// names, first-page text with digits stripped — see render.ts). Clopay has "a few versions"
// of the lien waiver, so the registry is keyed by fingerprint and ships EMPTY: a blank whose
// fingerprint is not here is held as `unrecognised_template` and listed on the Signatures →
// Templates page, where the layout is pinned by eye from a preview and then added HERE as a
// code change (reviewable, testable) — never guessed.
//
// Coordinates are PDF points with the origin at the page's bottom-left, as pdf-lib draws them.

export type FieldKind = 'text' | 'date' | 'signature' | 'customer_input'

/** Where a field's value comes from at render time. */
export type FieldSource =
  | 'customer_name' | 'address_line' | 'city' | 'state' | 'zip' | 'address_full'
  | 'po_numbers' | 'additional_pos' | 'order_number' | 'install_date' | 'sf_job_number' | 'installer_name' | 'today'
  | 'customer_input'                                  // typed by the customer on the signing page
  | 'customer_signature' | 'customer_signed_name' | 'customer_signed_date'
  | 'tech_signature' | 'tech_signed_name' | 'tech_signed_date'

export interface Box { page: number; x: number; y: number; w: number; h: number }

export interface FieldSpec {
  key: string
  kind: FieldKind
  source: FieldSource
  /** AcroForm field name, when the form has real fields. Preferred over `box` when present. */
  acro?: string
  /** Where to draw when there is no AcroForm field (flat PDF) or for signatures/images. */
  box?: Box
  /** For customer_input: the label shown on the signing page. */
  label?: string
  required?: boolean
  /** Text size ceiling; shrinks to fit the box. */
  size?: number
}

/** What the form certifies. Home Depot's Clopay forms come in two flavours: the 329 Customer
 *  Approval is signed after an INSTALL; the homedepot.com "Proof of Delivery" waiver is
 *  signed after a DELIVERY (no install by us). Customer messages must say the right one. */
export type TemplateService = 'install' | 'delivery'

export interface TemplateSpec {
  key: string
  vendor: string
  docType: string
  label: string
  service: TemplateService
  /** Every blank-form version this layout applies to. */
  fingerprints: string[]
  /** Text that identifies the version on its first page — Home Depot prints a form number and
   *  revision in the footer ("329 Customer Approval (02 Jun. 21)"), which survives layout-
   *  neutral regenerations better than any hash. Either a marker or a fingerprint matches. */
  markers?: RegExp[]
  fields: FieldSpec[]
}

export const TEMPLATES: TemplateSpec[] = [
  // Home Depot "Home Services Installation Customer Approval", form 329, revision 02 Jun 2021,
  // as generated by Clopay's portal (v113). One page, 611×843 pt. Clopay pre-fills the
  // customer, store, PO, job-site address, phones, the service-provider block AND the
  // "Additional PO(s)" line for a multi-door house — so this layout writes NOTHING over any
  // of those: signatures and their dates only. Labels sit BELOW their values on this form;
  // each signature goes on the line just above its label, next to the printed "X".
  // Pinned 2026-09-09 from four real blanks' text coordinates (pdf.js transforms), all
  // identical to the point.
  {
    key: 'hd329_2021_06', vendor: 'clopay_hd', docType: 'lien_waiver', label: 'HD form 329 Customer Approval (02 Jun 2021)', service: 'install',
    fingerprints: ['3ae7dbab259f9ab5'],   // computed from four real blanks, all identical
    markers: [/329\s+Customer\s+Approval\s*\(02\s*Jun\.?\s*21\)/i],
    fields: [
      // Service Provider (our technician) — line above "Service Provider Signature:" / "Date".
      { key: 'tech_sig', kind: 'signature', source: 'tech_signature', box: { page: 0, x: 44, y: 241, w: 290, h: 17 } },
      { key: 'tech_date', kind: 'date', source: 'tech_signed_date', box: { page: 0, x: 386, y: 241, w: 90, h: 12 }, size: 9 },
      // Certificate of Completion — line above "Customer Signature" / "Date", beside the printed name.
      { key: 'cust_sig', kind: 'signature', source: 'customer_signature', box: { page: 0, x: 287, y: 91, w: 195, h: 26 } },
      { key: 'cust_date', kind: 'date', source: 'customer_signed_date', box: { page: 0, x: 492, y: 93, w: 85, h: 12 }, size: 9 },
    ],
  },
  // "HOMEDEPOT.COM ORDER — Lien Waiver – Proof of Delivery": the waiver for a homedepot.com
  // DELIVERY (we deliver the door, we do not install it). One page, A4 595×842 pt, no
  // version footer — the whole page is one scaled form XObject. Clopay pre-fills the customer
  // block, the proposal number and "Installer's Company: CASTLE GARAGE INC", so again only
  // signatures and dates are written. Pinned 2026-09-09 from three real blanks: the customer
  // signature and "Date Completed" are drawn lines (x 63–237 and x 358–503 at y 619) with
  // their labels BELOW; the installer's signature and date are boxes (x 63–335 and x 335–528,
  // y 275–314) with the label printed inside at the left, so those go to the label's right.
  {
    key: 'hd_com_lw_pod', vendor: 'clopay_hd', docType: 'lien_waiver', label: 'homedepot.com Lien Waiver – Proof of Delivery', service: 'delivery',
    fingerprints: ['9b4c7db714746055'],
    markers: [/Lien\s+Waiver\s*[–—-]\s*Proof\s+of\s+Delivery/i],
    fields: [
      { key: 'cust_sig', kind: 'signature', source: 'customer_signature', box: { page: 0, x: 66, y: 621, w: 168, h: 26 } },
      { key: 'cust_date', kind: 'date', source: 'customer_signed_date', box: { page: 0, x: 362, y: 622, w: 138, h: 12 }, size: 9 },
      { key: 'tech_sig', kind: 'signature', source: 'tech_signature', box: { page: 0, x: 186, y: 278, w: 145, h: 33 } },
      { key: 'tech_date', kind: 'date', source: 'tech_signed_date', box: { page: 0, x: 372, y: 288, w: 150, h: 12 }, size: 9 },
    ],
  },
]

export function resolveTemplate(fingerprint: string | null | undefined, firstPageText?: string | null): TemplateSpec | null {
  if (fingerprint) {
    const byFp = TEMPLATES.find(t => t.fingerprints.includes(fingerprint))
    if (byFp) return byFp
  }
  if (firstPageText) {
    const text = firstPageText.replace(/\s+/g, ' ')
    const byMarker = TEMPLATES.find(t => (t.markers ?? []).some(re => re.test(text)))
    if (byMarker) return byMarker
  }
  return null
}

export function templateByKey(key: string | null | undefined): TemplateSpec | null {
  if (!key) return null
  return TEMPLATES.find(t => t.key === key) ?? null
}
