// Mock Google reviews for local dev and pre-API-approval testing.
// Flip to live data by setting the five GOOGLE_* env vars.

import type { GbpReview } from './gbp-client'

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86_400_000).toISOString()
}

export const MOCK_REVIEWS: GbpReview[] = [
  {
    googleReviewId: 'mock-001',
    reviewerName: 'Sarah Johnson',
    starRating: 5,
    comment: 'Absolutely fantastic service! The technician arrived right on time, diagnosed the issue with my garage door spring in minutes, and had it fixed within the hour. Very professional and friendly. Will definitely use Castle again!',
    createdAtGoogle: daysAgo(3),
    updatedAtGoogle: daysAgo(3),
    replyText: 'Thank you so much, Sarah! We\'re glad we could get your door back up and running quickly.',
    replyUpdatedAt: daysAgo(2),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-002',
    reviewerName: 'Mike T.',
    starRating: 5,
    comment: 'Called in the morning, tech was out by noon. Fixed my gate opener and also noticed my springs were getting worn — flagged it without any pressure to upsell. Honest, fast, fair price.',
    createdAtGoogle: daysAgo(7),
    updatedAtGoogle: daysAgo(7),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-003',
    reviewerName: 'Linda M.',
    starRating: 4,
    comment: 'Good experience overall. The repair was done well and the tech was knowledgeable. Took a little longer than quoted but they called ahead to let me know.',
    createdAtGoogle: daysAgo(12),
    updatedAtGoogle: daysAgo(12),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-004',
    reviewerName: 'Robert Chen',
    starRating: 5,
    comment: 'Second time using Castle and they never disappoint. New garage door installation looks great, and everything works perfectly. The crew was clean, efficient, and left no mess.',
    createdAtGoogle: daysAgo(15),
    updatedAtGoogle: daysAgo(15),
    replyText: 'Thanks Robert, we appreciate your continued trust in us!',
    replyUpdatedAt: daysAgo(14),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-005',
    reviewerName: 'A Google User',
    starRating: 5,
    comment: 'Great work.',
    createdAtGoogle: daysAgo(18),
    updatedAtGoogle: daysAgo(18),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-006',
    reviewerName: 'Jennifer Williams',
    starRating: 1,
    comment: 'Extremely disappointed. Technician was 3 hours late with no communication. When he finally arrived, the repair cost was double the estimate. Would not recommend.',
    createdAtGoogle: daysAgo(22),
    updatedAtGoogle: daysAgo(22),
    replyText: 'Jennifer, we sincerely apologize for this experience. Please contact us directly so we can make it right.',
    replyUpdatedAt: daysAgo(21),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-007',
    reviewerName: 'David K.',
    starRating: 5,
    comment: 'These guys are the best. Replaced both springs on my two-car garage and tuned everything up. Door is quieter than it\'s been in years. Fair pricing and great communication.',
    createdAtGoogle: daysAgo(25),
    updatedAtGoogle: daysAgo(25),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-008',
    reviewerName: 'Maria Garcia',
    starRating: 5,
    comment: 'Quick response, professional service. They explained everything before starting and the final bill matched the quote exactly. Very trustworthy company.',
    createdAtGoogle: daysAgo(30),
    updatedAtGoogle: daysAgo(30),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-009',
    reviewerName: 'Tom S',
    starRating: 3,
    comment: 'Service was okay. Tech seemed rushed and didn\'t fully explain the issue. Door works now but I\'m not confident it will last. Might look elsewhere next time.',
    createdAtGoogle: daysAgo(35),
    updatedAtGoogle: daysAgo(35),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-010',
    reviewerName: 'Patricia Lee',
    starRating: 5,
    comment: 'Same-day service! My garage door cable snapped on a Friday afternoon and they had someone out by 5pm. Couldn\'t believe how fast they responded. Excellent work.',
    createdAtGoogle: daysAgo(40),
    updatedAtGoogle: daysAgo(40),
    replyText: 'So glad we could help on short notice, Patricia!',
    replyUpdatedAt: daysAgo(39),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-011',
    reviewerName: 'James Wilson',
    starRating: 4,
    comment: 'Professional and efficient. Minor hiccup with scheduling but they sorted it out quickly. The actual repair was top notch.',
    createdAtGoogle: daysAgo(45),
    updatedAtGoogle: daysAgo(45),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-012',
    reviewerName: 'Susan B.',
    starRating: 5,
    comment: 'Outstanding! New gate opener installed perfectly. The tech walked me through programming all the remotes and the keypad. Very patient and thorough.',
    createdAtGoogle: daysAgo(50),
    updatedAtGoogle: daysAgo(50),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-013',
    reviewerName: 'Carlos Rivera',
    starRating: 5,
    comment: 'Honest pricing, quality parts, fast installation. What more do you want? Castle is now my go-to for anything garage or gate related.',
    createdAtGoogle: daysAgo(55),
    updatedAtGoogle: daysAgo(55),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-014',
    reviewerName: 'Nancy',
    starRating: 2,
    comment: 'Tech came out and said he fixed the problem but the door started making the same noise two days later. Had to call again. Not happy about paying twice for the same issue.',
    createdAtGoogle: daysAgo(60),
    updatedAtGoogle: daysAgo(60),
    replyText: 'Nancy, we\'re sorry to hear this. Please call us and we will make this right at no charge.',
    replyUpdatedAt: daysAgo(59),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-015',
    reviewerName: 'Kevin M.',
    starRating: 5,
    comment: 'Annual tune-up done quickly and professionally. Tech caught a few things that needed attention and fixed them on the spot. Good preventive maintenance program.',
    createdAtGoogle: daysAgo(65),
    updatedAtGoogle: daysAgo(65),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-016',
    reviewerName: 'Amy Thompson',
    starRating: 5,
    comment: 'Best garage door company I\'ve ever used. Knowledgeable staff, competitive pricing, and they stand behind their work. Five stars without hesitation.',
    createdAtGoogle: daysAgo(70),
    updatedAtGoogle: daysAgo(70),
    replyText: 'Thank you Amy, that means the world to us!',
    replyUpdatedAt: daysAgo(69),
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-017',
    reviewerName: 'J Martinez',
    starRating: 4,
    comment: 'Good service, friendly tech. A bit pricey for what it was but the quality of work was solid.',
    createdAtGoogle: daysAgo(80),
    updatedAtGoogle: daysAgo(80),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-018',
    reviewerName: 'Google User',
    starRating: 5,
    comment: null,
    createdAtGoogle: daysAgo(90),
    updatedAtGoogle: daysAgo(90),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-019',
    reviewerName: 'Barbara H.',
    starRating: 5,
    comment: 'Called at 8am, tech arrived at 10am, done by 11am. Broken spring replaced, door lubricated, tested everything. Perfect experience.',
    createdAtGoogle: daysAgo(95),
    updatedAtGoogle: daysAgo(95),
    replyText: null,
    replyUpdatedAt: null,
    rawPayload: { mock: true },
  },
  {
    googleReviewId: 'mock-020',
    reviewerName: 'Frank D.',
    starRating: 5,
    comment: 'Had Castle install a complete new door system — opener, springs, tracks, the works. The crew was professional, finished in one day, and the price was very fair. Highly recommend.',
    createdAtGoogle: daysAgo(110),
    updatedAtGoogle: daysAgo(110),
    replyText: 'Thank you Frank! Enjoy your new door!',
    replyUpdatedAt: daysAgo(109),
    rawPayload: { mock: true },
  },
]
